### ISSUE TITLE
 Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by yuxuan-ctrl** [pontjs/pontx#4]
使用pontx插件生成代码时，插件报错

![iwEcAqNwbmcDAQTRCawF0QV8BrDh6RyyKV6dPAUK8PbEP9MAB9MAAAAAkEnDUggACaJpbQoAC9IAAbwQ png_720x720q90](https://github.com/pontjs/pontx/assets/83435945/c9da77aa-4a92-4465-bc71-6208adb892c1)

**Comment by jasonHzq** [comment]
亲测 examples/hooks-app 启动正常，examples/hooks-app 是一个 Pontx 使用的配置示例。

这个报错，应该是你在使用 examples/hooks-app 前，运行了 lerna bootstrap， 将 examples/hooks-app 的依赖 link 到了本地 package 中。

使用 examples/hooks-app ，正常安装 examples/hooks-app 的 node_modules 即可。

**Comment by yuxuan-ctrl** [comment]
你测试的时候有执行lerna bootstrap命令嘛？麻烦看看你成功的时候，外层node_modules是否有各个插件的包
