### ISSUE TITLE
if baidu sdk fails, all the translator fails too

### ISSUE THREAD

**Issue by yuxuan-ctrl** [pontjs/pontx#5]
<img width="1280" alt="1696254706168" src="https://github.com/pontjs/pontx/assets/83435945/72ee9bf8-14f7-438b-96f7-f9b0b141d52b">

**Comment by jasonHzq** [comment]
Pontx 翻译器用来解决不正确的数据源，将中文变量名经过翻译转换为 camelCase 的英文变量名。

如使用百度翻译器，需配置自己的百度翻译 appId 和 secret，配置如下：

```json
{
  "outDir": "../src/pontx-services",
  "translate": {
    "cacheFilePath": "translateCache.json",
    "baidu": {
      "appId": "your app id",
      "secret": "your secret"
    }
  }
```

如百度翻译无法满足，Pontx 正在将翻译能力插件化，你可以开发自己的翻译器插件。

**Comment by yuxuan-ctrl** [comment]
我了解，我指的是有道和Google那些翻译插件已经用不了了，假如百度的那个插件失效，就阻塞了流程
