### ISSUE TITLE
Pont 创建失败:Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shenyanshu** [pontjs/pontx#9]
新创建的React项目，添加pontx-config.json后提示 “Pont 创建失败:Maximum call stack size exceeded”
![image](https://github.com/pontjs/pontx/assets/44387073/687bdd48-b510-4451-b6bb-a18bcaadf4d3)

**Comment by jasonHzq** [comment]
可以粘贴你的 pontx-config.json 配置吗

**Comment by jasonHzq** [comment]
排查到了，这是一个 Pontx 的 bug，在 windows 环境会触发，马上修复。

**Comment by jasonHzq** [comment]
fixed
